# Generated by Django 6.0.6 on 2026-06-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favourite_books',
            field=models.ManyToManyField(related_name='liked_accounts', to='main.book'),
        ),
    ]
