# Generated by Django 6.0.6 on 2026-06-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_favourite_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='favourite_books',
            field=models.ManyToManyField(blank=True, related_name='liked_accounts', to='main.book'),
        ),
    ]
